version: "3.8"

services:
  mongodb:
    image: mongo:6.0.6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # expose host port 27017 to container 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb_data:/data/db

volumes:
  mongodb_data:
