name: Deploy NestJS Project to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SERVER_PORT $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Sync project folder to server
        run: |
          rsync -avz -e "ssh -p $SERVER_PORT -i ~/.ssh/id_rsa" ./nestja/ $SERVER_USER@$SERVER_HOST:/home/ubuntu/nestja/

      - name: Deploy with docker compose on server
        run: |
          ssh -p $SERVER_PORT -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST "
            cd /home/ubuntu/nestja &&
            sudo docker compose down || true &&
            sudo docker compose up -d
          "

