name: Deploy MongoDB Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_USER: ${{ secrets.SERVER_USER }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p $SERVER_PORT "$SERVER_HOST" >> ~/.ssh/known_hosts

      - name: Deploy MongoDB on server
        run: |
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST << 'EOF'
          sudo docker compose -f /home/ubuntu/mongo-docker-compose.yml down || true
          sudo docker compose -f /home/ubuntu/mongo-docker-compose.yml up -d
          EOF
