name: Deploy Mongo to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          scp -P ${{ secrets.SERVER_PORT }} docker-compose.yml init-mongo.js "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST}}:/home/ubuntu/"
          ssh -p ${{ secrets.SERVER_PORT }} "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "
            sudo docker compose -f /home/ubuntu/docker-compose.yml down || true &&
            sudo docker compose -f /home/ubuntu/docker-compose.yml up -d
          "
