name: Mongo Setup

on: [push]

jobs:
  mongo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Start MongoDB (no .env used)
        run: docker-compose up -d

      - name: Wait and Test Mongo
        run: |
          sleep 15
          docker ps
          docker exec mongodb mongosh -u myuser -p mypassword --authenticationDatabase admin --eval "db.stats()"
