- name: Deploy to EC2
  env:
    SERVER_HOST: ${{ secrets.SERVER_HOST }}
    SERVER_USER: ${{ secrets.SERVER_USER }}
    SERVER_PORT: ${{ secrets.SERVER_PORT }}
    SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
  run: |
    echo "$SERVER_SSH_KEY" > private_key.pem
    chmod 600 private_key.pem

    scp -i private_key.pem -P "$SERVER_PORT" docker-compose.yml init-mongo.js "$SERVER_USER@$SERVER_HOST:/home/ubuntu/"

    ssh -i private_key.pem -p "$SERVER_PORT" "$SERVER_USER@$SERVER_HOST" "
      docker compose -f /home/ubuntu/docker-compose.yml down || true &&
      docker compose -f /home/ubuntu/docker-compose.yml up -d
    "

    rm -f private_key.pem
